🧪 test: 06: should handle new lines between numbers (instead of commas)
 FAIL  src/index.test.ts > incubyte-tdd-assessment: Kata 1: String Calculator > test 06: should handle new lines between numbers (instead of commas)
AssertionError: expected 4 to be 6 // Object.is equality

- Expected
+ Received

- 6
+ 4